### Task 1

In [38]:
Planetas = ["Mercurio","Venus","Tierra","Marte","Jupiter","Saturno","Urano","Neptuno"]
print(Planetas)

['Mercurio', 'Venus', 'Tierra', 'Marte', 'Jupiter', 'Saturno', 'Urano', 'Neptuno']


In [37]:
cantidad = len(Planetas)
print("Existen ",cantidad," planetas en el sistema solar")

Existen  8  planetas en el sistema solar


In [39]:
cuatro =Planetas[:4]
print("los primeros 4 planetas del sistema solar son ",cuatro)

los primeros 4 planetas del sistema solar son  ['Mercurio', 'Venus', 'Tierra', 'Marte']


In [20]:
ese = Planetas[1]

In [24]:
print("el planeta que termina con una s del sistema solar es ",ese)

el planeta que termina con una s del sistema solar es  Venus


## Task 2

In [30]:
temperaturaF = 30.3

In [33]:
temperaturaC = (5/9)*(temperaturaF-32)

In [36]:
print("la temperatura en Farenheit es de ",temperaturaF,",el cual en grados Celcius es de ",temperaturaC)

la temperatura en Farenheit es de  30.3 ,el cual en grados Celcius es de  -0.9444444444444441


## Task 3

In [1]:
import numpy as np

In [2]:
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

Reshape o reformular el array para que sea de 4x4.

In [5]:
# como debería de resultar
resultado = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(resultado)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# usaré reshape
array_2d = array_1d.reshape(4,4)
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Task 4

In [23]:
# Calcule el seno y el coseno de los ángulos: 0, 30, 45, 60 y 90 dados en grados
grados = np.array([0, 30, 45, 60, 90])
radianes = np.deg2rad(grados)

seno = np.sin(radianes)
coseno = np.cos(radianes)

print("Los grados en radianes son:", radianes, "\n", "los senos son:", seno, "\n","y los cosenos son:", coseno)

Los grados en radianes son: [0.         0.52359878 0.78539816 1.04719755 1.57079633] 
 los senos son: [0.         0.5        0.70710678 0.8660254  1.        ] 
 y los cosenos son: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


# Task 5

In [ ]:
# este está muy difícil